# ----
# Site

title: Welcome to the creatives
url: "https://jameswquinn.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/dev" # the subpath of your site, e.g. /blog
google_analytics_key:
google_maps_javascript_api_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
image: /asset/images/siteicon.png
description: > # this means to ignore newlines until "baseurl:"
  We are a leading Digital Agency with offices in London and Rome. Since 2006, we have helped many businesses go digital. From luxury fashion brands to pharmaceutical companies, by way of accountancy firms, our expertise is lavish, and our know-how is enviable. As a leading Magento & eCommerce agency, we have a thorough knowledge of each of the following sectors, because the difference between a fancy sequin blouse and Paracetamol is actually quite big, in the digital world. Le plat du jour? Web design, branding, eCommerce, social media and digital marketing.
  
author: ayuplus.io
name: ayuplus.io
email: support@ayuplus.io
twitter_creator: ANOther
social:
name: 
links:
    - https://github.com/CloudCannon/frisco-jekyll-template
    - https://github.com/CloudCannon/frisco-jekyll-template-etc


twitter_username: jekyllrb
github_username:  jekyll
twitter_creator: ANOther
# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
sass:
    sass_dir: _sass
    style: compressed
    
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
